// Convert a set of DX7 .syx bank files in Bulk Dump Packed Format to C arrays for the 2HPico PlaitsFM sketch
// Rich Heslip Feb 19/2026
//
// some code borrowed from wav2header Copyright 2014, Paul Stoffregen (paul@pjrc.com)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// compile with:  gcc -O2 -Wall -S -o sysex2bank sysex2bank.c
//  win32 cygwin:       i686-w64-mingw32-gcc -s -O2 -Wall sysex2bank.c -o sysex2bank.exe
// windows 10 cygwin64: x86_64-w64-mingw32-gcc -s -O2 -Wall sysex2bank.c -o sysex2bank.exe

// to use: put 8 (no more, no less!) DX7 .syx files in a temporary directory with this program
// run the program and it will convert the files to a single file "banks.cc"
// move "banks.cc" to your sketch folder and recompile PlaitsFM.ino

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <dirent.h>

const char *filename="";
unsigned int bcount,wcount;

void die(const char *format, ...)
{
	va_list args;
	va_start(args, format);
	fprintf(stderr, "wav2sketch: ");
	vfprintf(stderr, format, args);
	fprintf(stderr, "\n");
	exit(1);
}

uint8_t read_uint8(FILE *in)
{
	int c1;

	c1 = fgetc(in);
	if (c1 == EOF) die("byte read error, end of data while reading file %s\n",filename);
	c1 &= 255;
	return c1;
}


int main(int argc, char **argv)
{
	DIR *dir;
	struct dirent *f;
	struct stat s;
	FILE *fp, *outh=NULL;
	uint8_t header[6];
	uint8_t buffer[129];
	int filecount=0;

	dir = opendir(".");
	if (!dir) die("unable to open directory");
	
	outh = fopen("banks.cc", "w");  // sample structure definitions
	if (outh == NULL) die("unable to write output file banks.cc\n");
	fprintf(outh, "// File generated by sysex2bank \n\n");
	
	fprintf(outh, "#include \"plaits/resources.h\"\n\n");
	fprintf(outh, "namespace plaits {\n\n");
	
	while (1) {
		f = readdir(dir);
		if (!f) break;
		if (stat(f->d_name, &s) < 0) continue; // skip if unable to stat
		if (S_ISDIR(s.st_mode)) continue;  // skip directories
		if (!S_ISREG(s.st_mode)) continue; // skip special files
		filename = f->d_name;
		int len=strlen(filename);
		if (len< 5) continue; // can't be a .syx file so skip it 
		if (strcasecmp(filename + len - 4, ".syx") != 0) continue;
		fp = fopen(filename, "rb");
		if (!fp) die("unable to read file %s\n", filename);
		printf("converting: %s\n", filename);
		fprintf(outh, "// file  %s \n", filename ); //
		fprintf(outh, "const uint8_t syx_bank_%1d[] = {", filecount ); //
		
		fread(&header, 6L, 1, fp);
		
		for (int count=0;count<32;count++) {			
			for (int i=0;i<128;++i) buffer[i]=read_uint8(fp);
			buffer[128]=0; // nul terminate patch name
			fprintf(outh, "\n// %2d %s\n\t",count+1,&buffer[118]); // print patch name
			for (int j=0;j<8;++j) {
				for (int c=0;c<16;++c) fprintf(outh, "%4d,", buffer[c+j*16]);
				fprintf(outh, "\n\t");
			}
		}
		fprintf(outh, "\n};\n\n"); // 		
		fclose(fp);
		if (++filecount >=8) break;
	}
	fprintf(outh, "}; // namespace plaits\n"); // end sampledefs.h initializer section
	fclose(outh);
	printf("%d files processed\n",filecount);
	if (filecount !=8) printf ("**** WARNING - sysex2bank requires 8 sysex files as input, %d found ****\n",filecount);
	return 0;
}


